### ISSUE TITLE
Java request

### ISSUE THREAD

**Issue by munenek** [Aurum1611/DarkModePreferencesTutorial#1]
Hey could you do this in Java

**Comment by neeyatlotlikar** [comment]
@munenek Yes, sure. I'll do so, upload the repository, and I'll let you know in this thread.

**Comment by neeyatlotlikar** [comment]
@munenek I have created a Java counterpart for this project. Visit this link: [DarkModePreferenceTutorialJava](https://github.com/Aurum1611/DarkModePreferenceTutorialJava). I hope this is helpful.

**Comment by munenek** [comment]
Thank you. This was very helpful.
